<?php 
/**
 * Magiccart 
 * @category 	Magiccart 
 * @copyright 	Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license 	http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2016-04-31 17:55:44
 * @@Modify Date: 2017-08-31 18:40:08
 * @@Function:
 */

	//echo $this->getThemecfg() 

	$cfg = $this->_themeCfg;
	$html ='';
	$font 	= $cfg['font'];
	/* get Lib Font */
	if($font['google']) $html  = '<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family='.str_replace(' ', '+', $font['google']).'&subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese" media="all" />';
	$html  .= "\n"; // break line;
	/* CssGenerator */
	$html  .= '<style type="text/css">';
	$html  .= 'body{ font-size: '.$font['size'].'; font-family: '.$font['google'].';}';

	$design = $this->_scopeConfig->getValue( 'alodesign', \Magento\Store\Model\ScopeInterface::SCOPE_STORE );
		foreach ($design as $group => $options) 
		{
			foreach ($options as $property => $values) {
				$tmp = json_decode($values, true);
				if(json_last_error() == JSON_ERROR_NONE){
					$values = $tmp;
				} else {
					$values = @unserialize($values);
				}
				if(is_array($values) || is_object($values)){
					foreach ($values as $value) {
						if(!$value) continue;
						$html .= htmlspecialchars_decode($value['selector']) .'{';
							$html .= $value['color'] 		? 'color:' .$value['color']. ';' 					: '';
							$html .= $value['background'] 	? ' background-color:' .$value['background']. ';' 	: '';
							$html .= $value['border'] 		? ' border-color:' .$value['border']. ';' 			: '';
						$html .= '}';
					}				
				}

			}
		}
	$html  .= '</style>';
	$html  .= "\n"; // break line;
	$cfg['general']['baseUrl'] = $this->getBaseUrl();
	$optRm = array('font', 'grid', 'related', 'upsell', 'crosssell', 'labels', 'timer', 'categorysearch');
	foreach ($optRm as $opt) { unset($cfg[$opt]); }
	$html .= '<script type="text/javascript"> Themecfg = '.json_encode($cfg).'</script>';  // json config theme
	echo $html;

	$timer = $this->_themeCfg['timer'];
	// if(!$timer['enabled']) return;
	$layout = '<span class="day">%%D%%</span><span class class="colon">:</span><span class="hour">%%H%%</span><span class="colon">:</span><span class="min">%%M%%</span><span class="colon">:</span><span class="sec">%%S%%</span>';

	$layoutcaption = '<div class="timer-box"><span class="day">%%D%%</span><span class="title">' . __('Days') . '</span></div><div class="timer-box"><span class="hour">%%H%%</span><span class="title">' . __('Hrs')  . '</span></div><div class="timer-box"><span class="min">%%M%%</span><span  class="title">' . __('Mins') . '</span></div><div class="timer-box"><span class="sec">%%S%%</span><span  class="title">' . __('Secs') . '</span></div>';	
	if($timer['caption']){
		$layout = $layoutcaption;
	}
?>
<script type="text/javascript">
	var alo_timer_layout 		= '<?php echo $layout ?>';
	var alo_timer_layoutcaption = '<?php echo $layoutcaption ?>';
	var alo_timer_timeout 		= '<span class="timeout"><?php echo __('Time out!')?></span>';
	<?php //if(isset($cfg['rtl']) && $cfg['rtl'] ) echo "document.body.className += ' rtl';"; ?>
	require(['jquery','magiccart/slick','alothemes']);
</script>
