<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */

?> 
<link href="//fonts.googleapis.com/css?family=Rajdhani:300,400,500,600,700&amp;subset=devanagari,latin-ext" rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Poppins:300,400,500,600,700&amp;subset=devanagari,latin-ext" rel="stylesheet">
<?php
	$rtl = $this->helper('Magiccart\Alothemes\Helper\Data')->getConfig('alothemes/rtl/enabled');
	if($rtl) echo '<script type="text/javascript">document.body.className += " rtl"</script>';
?>
<header class="page-header alothemes">
    <div class="header">
		<div class="header-content">
		    <div class="header-sticker-none">
				<div class="full-width">
					<div class="container">
						<div class="main-fix head-position clearfix">
							<div class="clearfix">
								<div class="content-logo">
									<div class="header-logo">
										<?php echo $this->getChildHtml('logo'); ?>
									</div>
								</div>
								<div class="header-icons content-cart clearfix">
									<div class="tool-header">
										<div class="top-link-product">
											<a title="My wishlist" href="<?php echo $this->getUrl('wishlist') ?>" target="_blank" class="wishlist icon ion-android-favorite-outline alotheme-tooltip">
											 <?php $counter = $this->helper('Magento\Wishlist\Helper\Data')->getItemCount() ?>
												<?php if($counter): ?>
													<span class="counter"><?php echo $counter > 0 ? $counter:0; ?></span>
												<?php endif; ?>
												<!-- <span class="tooltip"><?php /* echo __('Wish List') */?></span>-->
											</a>
										</div>
										<div class="closetab">
											<div class="alo-toggle tool-topsearch toggle-tab-mobile">
												<span class="toggle-tab outside-close mobile"><i class="icon ion-ios-search-strong icons"></i></span>
												<div class="over-lay"></div>
												<div class="dropdown-switcher toggle-content">
													<div class="top-search-alo container">
														<h3 class="search-title"><?php /* @escapeNotVerified */ echo __('Search') ?></h3>
														<?php echo $this->getChildHtml('top.search'); ?>
														<div class="button btn-close"><span><?php /* @escapeNotVerified */ echo __('close') ?></span></div>
													</div>
												</div>
											</div>
										</div>
										<?php echo $this->getChildHtml('minicart'); ?>
										<div class="closetab">
											<div class="alo-toggle tool-account toggle-tab-mobile">
												<span class="toggle-tab outside-close mobile"><i class="icon ion-android-settings-none ion-android-more-vertical icons"></i></span>
												<div class="dropdown-switcher toggle-content">
													<div class="button btn-close"><span><?php /* @escapeNotVerified */ echo __('close') ?></span></div>
													<?php echo $this->getChildHtml('header.links'); ?>
													<div class="header-setting">
														<div class="settting-switcher">
															<?php echo $this->getChildHtml('currency'); ?>
														</div>
													</div>
													<div class="header-setting">
														<div class="settting-switcher">
															<?php echo $this->getChildHtml('store_language'); ?>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class="under-top-bar vertical-menu menu-mobile-none">
									<?php echo $this->getChildHtml('navigation.sections'); ?>
								</div>
								<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('social')->toHtml();?>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>		
	</div>
</header>
