<?php
	$dataHelper = $this->helper('Tactconnect\PassEncryption\Helper\Data');
	$customerSession = $dataHelper->getCustomerSession();
	$randomString = md5(time().$dataHelper->getRandomString(16)); 
	 $request = $this->getRequest();
	 $modulename = $request->getModuleName();
	 $controller = $request->getControllerName();
	 $action = $request->getActionName();
	 if($modulename == 'customer' && $controller == 'account' && $action == 'login')
	 {
	   $customerSession->setCustomerLoginEncryptionKey($randomString);
	 }

	 if($modulename == 'customer' && $controller == 'account' && $action == 'create')
	 {
	   $customerSession->setCustomerCreateEncryptionKey($randomString);
	 }
	
?>
<script>
	
	require(['jquery', 'mage/validation', 'Tactconnect_PassEncryption/js/aes'], function ($){
		var formSelector, dataForm;
		if($('.form-login').length)
		{
			formSelector = '.form-login';
			dataForm = $('.form-login');
		}
		if($('.form-create-account').length)
		{
			formSelector = '.form-create-account';
			dataForm = $('.form-create-account');
		}
		
	    var ignore = null;
	    var salt = '<?php echo $randomString; ?>';
	    var key = CryptoJS.enc.Hex.parse(salt + salt);
		var iv = CryptoJS.enc.Hex.parse(salt);
	    dataForm.mage('validation', {
	        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
	    }).find('input:text').attr('autocomplete', 'off');

		$(document).ready(function (){
			$(formSelector + ' .action.primary').on('click', function (e){
				//$('.form-login').submit();
				e.preventDefault();
				// e.stopImmediatePropagation();
				// e.stopPropagation();
				if(dataForm.validation('isValid'))
				{
					// var encryptMethod = 'AES-256-CBC';
					// var aesNumber = encryptMethod.match(/\d+/)[0];
					var pass = document.getElementById("pass").value;
					//var hide=document.getElementById("hide").value;
					if(formSelector == '.form-login')
						{
							pass = document.getElementById("pass").value;
						}
						else
						{
							pass = document.getElementById("password").value;
							//document.getElementById("password-confirmation").value =hash;
						}

					if(pass)
					{
						e.preventDefault();
						//console.log('pass' + pass);
						var hash = CryptoJS.AES.encrypt(pass, key, {iv:iv});
						
						if(formSelector == '.form-login')
						{
							document.getElementById("pass").value =hash;
						}
						else
						{
							document.getElementById("password").value =hash;
							document.getElementById("password-confirmation").value =hash;
						}
						//console.log('hash' + hash);
						$(formSelector).submit();
						//return true;
					}
				}
				
			});
		});
	});
</script>