<?php
	$dataHelper = $this->helper('Tactconnect\PassEncryption\Helper\Data');
	$customerSession = $dataHelper->getCustomerSession();
	$randomString = md5(time().$dataHelper->getRandomString(16)); 
	 // if($modulename == 'customer' && $controller == 'account' && $action == 'login')
	 // {
	 //   $customerSession->setCustomerLoginEncryptionKey($randomString);
	 // }

	 // if($modulename == 'customer' && $controller == 'account' && $action == 'create')
	 // {
	 //   $customerSession->setCustomerCreateEncryptionKey($randomString);
	 // }
	$customerSession->setFrontendResetPasswordEncryptionKey($randomString);
	
?>
<script>
	
	require(['jquery', 'mage/validation', 'Tactconnect_PassEncryption/js/aes'], function ($){
		var formSelector = '.form.password.reset', dataForm = $('.form.password.reset');
		// if($('.form-login').length)
		// {
		// 	formSelector = '.form-login';
		// 	dataForm = $('.form-login');
		// }
		// if($('.form-create-account').length)
		// {
		// 	formSelector = '.form-create-account';
		// 	dataForm = $('.form-create-account');
		// }
		
	    var ignore = null;
	    var salt = '<?php echo $randomString; ?>';
	    var key = CryptoJS.enc.Hex.parse(salt + salt);
		var iv = CryptoJS.enc.Hex.parse(salt);
	    // dataForm.mage('validation', {
	    //     ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
	    // }).find('input:text').attr('autocomplete', 'off');

		$(document).ready(function (){
			$(formSelector + ' .action.primary').on('click', function (e){
				//$('.form-login').submit();
				e.preventDefault();
				// e.stopImmediatePropagation();
				// e.stopPropagation();
				var hash;
				if(dataForm.validation('isValid'))
				{
				
					var pass = document.getElementById("password").value;
					if(pass)
					{
						//e.preventDefault();
						//console.log('pass' + pass);
						hash = CryptoJS.AES.encrypt(pass, key, {iv:iv});
						document.getElementById("password").value =hash;
						//console.log('hash' + hash);
						
						//return true;
					}
					pass = document.getElementById("password-confirmation").value;
					
					if(pass)
					{
						//console.log('pass' + pass);
						hash = CryptoJS.AES.encrypt(pass, key, {iv:iv});
						document.getElementById("password-confirmation").value =hash;
						//console.log('hash' + hash);
						
						//return true;
					}
					$(formSelector).submit();
				}
				
			});
		});
	});
</script>