<?php
?>
<script>
	
	require(['jquery', 'mage/validation', 'Tactconnect_PassEncryption/js/aes'], function ($){
		var formSelector, dataForm;
		if($('.form-login').length)
		{
			formSelector = '.form-login';
			dataForm = $('.form-login');
		}
		if($('.form-create-account').length)
		{
			formSelector = '.form-create-account';
			dataForm = $('.form-create-account');
		}
		
		console.log('formSelector' + formSelector);
	    var ignore = null;
	    var key = CryptoJS.enc.Hex.parse("a6d09dbffa488df48ebf273727ebebe1b08a5691eeeae8d59e401255073a3af8");
		var iv = CryptoJS.enc.Hex.parse("a5f65b2ee53eab72f26091421363a033");
	    dataForm.mage('validation', {
	        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
	    }).find('input:text').attr('autocomplete', 'off');

		$(document).ready(function (){
			$(formSelector + ' .action.primary').on('click', function (e){
				//$('.form-login').submit();
				e.preventDefault();
				// e.stopImmediatePropagation();
				// e.stopPropagation();
				if(dataForm.validation('isValid'))
				{
					// var encryptMethod = 'AES-256-CBC';
					// var aesNumber = encryptMethod.match(/\d+/)[0];
					var pass = document.getElementById("pass").value;
					//var hide=document.getElementById("hide").value;
					if(formSelector == '.form-login')
						{
							pass = document.getElementById("pass").value;
						}
						else
						{
							pass = document.getElementById("password").value;
							//document.getElementById("password-confirmation").value =hash;
						}

					if(pass)
					{
						e.preventDefault();
						//console.log('pass' + pass);
						var hash = CryptoJS.AES.encrypt(pass, key, {iv:iv});
						
						if(formSelector == '.form-login')
						{
							document.getElementById("pass").value =hash;
						}
						else
						{
							document.getElementById("password").value =hash;
							document.getElementById("password-confirmation").value =hash;
						}
						//console.log('hash' + hash);
						$(formSelector).submit();
						//return true;
					}
				}
				
			});
		});
	});
</script>