<?php
	$dataHelper = $this->helper('Tactconnect\PassEncryption\Helper\Data');
	$backendSession = $dataHelper->getBackendSession();
	$randomString = md5(time().$dataHelper->getRandomString(16));
	$backendSession->setBackendResetPasswordEncryptionKey($randomString);
?>
<script>
	
	require(['jquery', 'mage/validation', 'Tactconnect_PassEncryption/js/aes'], function ($){
		var formSelector = '#reset-password-form', dataForm = $('#reset-password-form');

	    var ignore = null;
	    var salt = '<?php echo $randomString; ?>';
	    var key = CryptoJS.enc.Hex.parse(salt + salt);
		var iv = CryptoJS.enc.Hex.parse(salt);
	    dataForm.mage('validation', {
	        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
	    }).find('input:text').attr('autocomplete', 'off');

		$(document).ready(function (){
			$(formSelector + ' .action-primary').on('click', function (e){
				//$('.form-login').submit();
				e.preventDefault();
				// e.stopImmediatePropagation();
				// e.stopPropagation();
				if(dataForm.validation('isValid'))
				{
					// var encryptMethod = 'AES-256-CBC';
					// var aesNumber = encryptMethod.match(/\d+/)[0];
					//var hide=document.getElementById("hide").value;
					var pass = document.getElementById("password").value;
					if(pass)
					{
						//e.preventDefault();
						//console.log('pass' + pass);
						hash = CryptoJS.AES.encrypt(pass, key, {iv:iv});
						document.getElementById("password").value =hash;
						//console.log('hash' + hash);
						
						//return true;
					}
					pass = document.getElementById("confirmation").value;
					
					if(pass)
					{
						//console.log('pass' + pass);
						hash = CryptoJS.AES.encrypt(pass, key, {iv:iv});
						document.getElementById("confirmation").value =hash;
						//console.log('hash' + hash);
						
						//return true;
					}
					$(formSelector).submit();
				}
				
			});
		});
	});
</script>