<?php
	$brand = $this->getBrand();
	if(!$brand) return;
?>
<div class="brand">
    <!-- <h2><?php echo __('Brand') ?></h2> -->
	<a href="<?php echo $this->getUrlBrand($brand) ?>">
		<span><?php echo __($brand->getLabel()) ?></span>
		<?php if($brand->getData('image')) : ?>
		<img class="brand img-responsive" src="<?php echo $this->getImage($brand)?>" alt="<?php echo __($brand->getTitle()) ?>" title="<?php echo __($brand->getTitle()) ?>" />
		<?php endif ?>
	</a>
</div>
