<?php
   $availableDistrict = $this->getAvailableDistrict();
   $cmsPages = $this->getCmsPages();
   //~ $getProductsByTag = $this->getProductsByTag('Agra');
   
   //~ echo '<pre>##';
   //~ print_r($availableDistrict->getData());
   //~ print_r($cmsPages->getData());
   
   ?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$mediaUrl =  $objectManager->get('Magento\Store\Model\StoreManagerInterface')
                    ->getStore()
                    ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$baseUrl = $objectManager->get('Magento\Store\Model\StoreManagerInterface')
                    ->getStore()->getBaseUrl();
?>
   
   
<div class="page-layout-2columns-left ">
   <div class="columns">
      <div class="column main">
         <?php if($availableDistrict->getSize() > 0): ?>
			 <div class="category-products clearfix products wrapper grid products-grid">
				<ol class="products list items product-items">
					<?php foreach($availableDistrict as $availableDis){
						
						$link = 'javascript:void(0)';
						//~ $link = 'https://odopmart.com/custom-chikankari-zari-zardozi.html';
						if($availableDis->getDistrictName() == 'Agra'){
							$link = $baseUrl.'custom-leather.html';
						}else if($availableDis->getDistrictName() == 'Lucknow'){
							$link = $baseUrl.'custom-chikankari-zari-zardozi.html';
						}else if($availableDis->getDistrictName() == 'Varanasi'){
							$link = $baseUrl.'clothing/silk.html';
						}else if($availableDis->getDistrictName() == 'Bhadohi'){
							$link = $baseUrl.'accessories/carpet.html';
						}else if($availableDis->getDistrictName() == 'Aligarh'){
							$link = $baseUrl.'accessories/brass-statue.html';
						}else if($availableDis->getDistrictName() == 'Muradabad'){
							$link = $baseUrl.'accessories/brass-handicraft.html';
						}else if($availableDis->getDistrictName() == 'Mirzapur'){
							$link = $baseUrl.'accessories/carpet.html';
						}else if($availableDis->getDistrictName() == 'Khujra'){
							$link = $baseUrl.'accessories/pottery.html';
						}else if($availableDis->getDistrictName() == 'Saharanpur'){
							$link = $baseUrl.'accessories/wood.html';
						}else if($availableDis->getDistrictName() == 'Meerut'){
							$link = $baseUrl.'sports-products.html';
						}
						
						
						 ?>
				   <li class="item product product-item">
					  <div class="product-item-info per-product category-products-grid" data-container="product-grid">
						 <div class="images-container">
							 <div class="product details product-item-details products-textlink">
							   <h2 class="product name product-name product-item-name">
								  <a class="product-item-link" href="<?php echo $link; ?>" title="<?php echo $availableDis->getPopularProduct(); ?>">
								  <?php echo $availableDis->getDistrictName(); ?>
								  </a>
							   </h2>
							</div>
							<div class="product-hover">
							   <a href="<?php echo $link; ?>" class="product photo product-item-photo" tabindex="-1">
							   <span class="product-image-container" style="width:370px;">
							   <span class="product-image-wrapper" style="padding-bottom: 128.10810810811%;">
							   <img class="product-image-photo" src="<?php echo $mediaUrl.$availableDis->getDistrictImage(); ?>" max-width="370" max-height="474" alt="Stone Wash 4*6"></span>
							   </span>
							   </a>
							</div>
							<div class="product details product-item-details products-textlink">
							   <h2 class="product name product-name product-item-name">
								  <a class="product-item-link" href="<?php echo $link; ?>" title="<?php echo $availableDis->getPopularProduct(); ?>">
								  <?php echo $availableDis->getPopularProduct(); ?>
								  </a>
							   </h2>
							</div>
						 </div>
					  </div>
					  
				   </li>
				   <?php	} ?>
				</ol>
			 </div>
			<?php else: ?>
				<div class="message info empty">
				<div><?php echo __('We cant find products matching the selection.'); ?></div>
			 </div>
			<?php endif; ?>
      </div>
      <div class="sidebar sidebar-main"></div>
      <div class="sidebar sidebar-additional">
         <ul class="uc-sidebar-menu"><span class="uc-sidebar-title"><?php echo __('One District One Product');?></span>
            <?php	
               foreach($cmsPages as $cmsPage){
				   if(in_array($cmsPage->getIdentifier(), ['home', 'president-message', 'prime-minister-message', 'chief-minister-message', 'about-us'])){
               ?>
            <li><a href="<?php echo $this->getUrl($cmsPage->getIdentifier()); ?>"><?php echo $cmsPage->getTitle(); ?></a></li>
            <?php }
            } ?>
         </ul>
      </div>
   </div>
</div>
